package lib

var (
	// Common
	CANNON = newCard(map[Attribute]interface{}{
		NAME:     "Cannon",
		ARENA:    ARENA_3,
		RARITY:   COMMON,
		TYPE:     BUILDING,
		DESC:     `Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops.`,
		COST:     3,
		BASE_HP:  450,
		DPS:      []int{75, 82, 90, 98, 108, 120, 131, 143, 158, 173, 191, 210},
		BASE_DAM: 60,
		HSPD:     0.8,
		TGTS:     GROUND,
		RNG:      6,
		DTIME:    1,
		LTIME:    30,
	})
	TESLA = newCard(map[Attribute]interface{}{
		NAME:     "Tesla",
		ARENA:    ARENA_4,
		RARITY:   COMMON,
		TYPE:     BUILDING,
		DESC:     `Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded.`,
		COST:     4,
		BASE_HP:  400,
		DPS:      []int{80, 88, 96, 106, 116, 128, 140, 153, 168, 185, 203, 223},
		BASE_DAM: 64,
		HSPD:     0.8,
		TGTS:     AIR_AND_GROUND,
		RNG:      6,
		DTIME:    1,
		LTIME:    40,
	})
	MORTAR = newCard(map[Attribute]interface{}{
		NAME:      "Mortar",
		ARENA:     ARENA_6,
		RARITY:    COMMON,
		TYPE:      BUILDING,
		DESC:      `Defensive building with a long range. Shoots exploding shells that deal area damage. Cannot shoot at targets that get very close!`,
		COST:      4,
		BASE_HP:   600,
		DPS:       []int{24, 26, 29, 31, 35, 38, 42, 46, 50, 55, 61, 67},
		BASE_ADAM: 120,
		HSPD:      5,
		TGTS:      GROUND,
		RNG:       12,
		DTIME:     3,
		LTIME:     30,
	})

	// Rare
	GOBLIN_HUT = newCard(map[Attribute]interface{}{
		NAME:        "Goblin Hut",
		ARENA:       ARENA_1,
		RARITY:      RARE,
		TYPE:        BUILDING,
		DESC:        `Building that spawns Spear Goblins. But don't look inside. You don't want to see how they are made.`,
		COST:        5,
		BASE_HP:     700,
		BASE_SGO_LV: 3,
		SSPD:        4.9,
		DTIME:       1,
		LTIME:       60,
	})
	BOMB_TOWER = newCard(map[Attribute]interface{}{
		NAME:      "Bomb Tower",
		ARENA:     ARENA_2,
		RARITY:    RARE,
		TYPE:      BUILDING,
		DESC:      `Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it.`,
		COST:      5,
		BASE_HP:   900,
		DPS:       []int{62, 68, 75, 83, 91, 100, 110, 120, 132, 145},
		BASE_ADAM: 100,
		HSPD:      1.6,
		TGTS:      GROUND,
		RNG:       6.5,
		DTIME:     1,
		LTIME:     60,
	})
	TOMBSTONE = newCard(map[Attribute]interface{}{
		NAME:        "Tombstone",
		ARENA:       ARENA_2,
		RARITY:      RARE,
		TYPE:        BUILDING,
		DESC:        `Troop building that periodically deploys Skeletons to fight the enemy. When destroyed, spawns 4 Skeletons. Creepy!`,
		COST:        3,
		BASE_HP:     200,
		BASE_SKE_LV: 3,
		SSPD:        2.9,
		DTIME:       1,
		LTIME:       40,
	})
	BARBARIAN_HUT = newCard(map[Attribute]interface{}{
		NAME:        "Barbarian Hut",
		ARENA:       ARENA_3,
		RARITY:      RARE,
		TYPE:        BUILDING,
		DESC:        `Troop building that periodically deploys Barbarians to fight the enemy. Time to make the Barbarians.`,
		COST:        7,
		BASE_HP:     1100,
		BASE_BAR_LV: 3,
		SSPD:        14,
		DTIME:       1,
		LTIME:       60,
	})
	INFERNO_TOWER = newCard(map[Attribute]interface{}{
		NAME:      "Inferno Tower",
		ARENA:     ARENA_6,
		RARITY:    RARE,
		TYPE:      BUILDING,
		DESC:      `Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!`,
		COST:      5,
		BASE_HP:   800,
		DPSL:      []int{50, 55, 60, 65, 72, 80, 87, 95, 105, 115},
		DPSH:      []int{1000, 1100, 1210, 1330, 1460, 1600, 1760, 1930, 2120, 2330},
		BASE_DAML: 20,
		BASE_DAMH: 400,
		HSPD:      0.4,
		TGTS:      AIR_AND_GROUND,
		RNG:       6.5,
		DTIME:     1,
		LTIME:     40,
	})
	ELIXIR_COLLECTOR = newCard(map[Attribute]interface{}{
		NAME:    "Elixir Collector",
		ARENA:   ARENA_6,
		RARITY:  RARE,
		TYPE:    BUILDING,
		DESC:    `You gotta spend Elixir to make Elixir.`,
		COST:    5,
		BASE_HP: 800,
		PSPD:    9.8,
		DTIME:   1,
		LTIME:   70,
	})

	// Epic
	X_BOW = newCard(map[Attribute]interface{}{
		NAME:     "X-Bow",
		ARENA:    ARENA_3,
		RARITY:   EPIC,
		TYPE:     BUILDING,
		DESC:     `Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the arena...`,
		COST:     6,
		BASE_HP:  850,
		DPS:      []int{66, 73, 80, 86, 96, 106, 116, 126},
		BASE_DAM: 20,
		HSPD:     0.3,
		TGTS:     GROUND,
		RNG:      12,
		DTIME:    5,
		LTIME:    40,
	})
)
