package lib

var (
	// Common
	KNIGHT = NewCard(map[Attribute]interface{}{
		NAME:   "Knight",
		ARENA:  ARENA_0,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.`,
		COST:   3,
		HP:     generateHp(600),
		DPS:    []int{68, 74, 81, 90, 99, 109, 120, 130, 144, 158, 174, 190},
		DAM:    generateDam(75),
		HSPD:   1.1,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    MELEE,
		DTIME:  1,
	})
	ARCHERS = NewCard(map[Attribute]interface{}{
		NAME:   "Archers",
		ARENA:  ARENA_0,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `A pair of unarmored ranged attackers. They'll help you with ground and air unit attacks, but you're on your own with coloring your hair.`,
		COST:   3,
		HP:     generateHp(125),
		DPS:    []int{33, 36, 40, 44, 48, 53, 58, 64, 70, 77, 85, 93},
		DAM:    generateDam(40),
		HSPD:   1.2,
		TGTS:   AIR_AND_GROUND,
		SPD:    MEDIUM,
		RNG:    5.5,
		DTIME:  1,
		COUNT:  2,
	})
	BOMBER = NewCard(map[Attribute]interface{}{
		NAME:   "Bomber",
		ARENA:  ARENA_0,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.`,
		COST:   3,
		HP:     generateHp(150),
		DPS:    []int{52, 57, 63, 70, 76, 84, 92, 101, 111, 122, 134, 147},
		ADAM:   generateDam(100),
		HSPD:   1.9,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    5,
		DTIME:  1,
	})
	GOBLINS = NewCard(map[Attribute]interface{}{
		NAME:   "Goblins",
		ARENA:  ARENA_1,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Three fast, unarmored melee attackers. Small, fast, green and mean!`,
		COST:   2,
		HP:     generateHp(80),
		DPS:    []int{45, 50, 54, 60, 66, 72, 80, 87, 96, 105, 116, 127},
		DAM:    generateDam(50),
		HSPD:   1.1,
		TGTS:   GROUND,
		SPD:    VERY_FAST,
		RNG:    MELEE,
		DTIME:  1,
		COUNT:  3,
	})
	SPEAR_GOBLINS = NewCard(map[Attribute]interface{}{
		NAME:   "Spear Goblins",
		ARENA:  ARENA_1,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Three unarmored ranged attackers. Who the heck taught these guys to throw spears!?! Who thought that was a good idea?!`,
		COST:   2,
		HP:     generateHp(52),
		DPS:    []int{18, 20, 22, 23, 26, 29, 32, 35, 38, 42, 46, 51},
		DAM:    generateDam(24),
		HSPD:   1.3,
		TGTS:   AIR_AND_GROUND,
		SPD:    VERY_FAST,
		RNG:    5.5,
		DTIME:  1,
		COUNT:  3,
	})
	SKELETONS = NewCard(map[Attribute]interface{}{
		NAME:   "Skeletons",
		ARENA:  ARENA_2,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Four fast, very weak melee fighters. Swarm your enemies with this pile of bones!`,
		COST:   1,
		HP:     generateHp(30),
		DPS:    V30[0:12:12],
		DAM:    generateDam(30),
		HSPD:   1,
		TGTS:   GROUND,
		SPD:    FAST,
		RNG:    MELEE,
		DTIME:  1,
		COUNT:  4,
	})
	MINIONS = NewCard(map[Attribute]interface{}{
		NAME:   "Minions",
		ARENA:  ARENA_2,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!`,
		COST:   3,
		HP:     generateHp(90),
		DPS:    V40[0:12:12],
		DAM:    generateDam(40),
		HSPD:   1,
		TGTS:   AIR_AND_GROUND,
		SPD:    FAST,
		RNG:    2.5,
		DTIME:  1,
		COUNT:  3,
	})
	BARBARIANS = NewCard(map[Attribute]interface{}{
		NAME:   "Barbarians",
		ARENA:  ARENA_3,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `A horde of melee attackers with mean mustaches and even meaner tempers.`,
		COST:   5,
		HP:     generateHp(300),
		DPS:    []int{50, 54, 60, 66, 72, 80, 88, 96, 106, 116, 128, 140},
		DAM:    generateDam(75),
		HSPD:   1.5,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    MELEE,
		DTIME:  1,
		COUNT:  4,
	})
	MINION_HORDE = NewCard(map[Attribute]interface{}{
		NAME:   "Minion Horde",
		ARENA:  ARENA_4,
		RARITY: COMMON,
		TYPE:   TROOP,
		DESC:   `Six fast, unarmored flying attackers. Three's a crowd, six is a horde!`,
		COST:   5,
		HP:     generateHp(90),
		DPS:    V40[0:12:12],
		DAM:    generateDam(40),
		HSPD:   1,
		TGTS:   AIR_AND_GROUND,
		SPD:    FAST,
		RNG:    2.5,
		DTIME:  1,
		COUNT:  6,
	})

	// Rare
	GIANT = NewCard(map[Attribute]interface{}{
		NAME:   "Giant",
		ARENA:  ARENA_0,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `Slow but durable, only attacks buildings. A real one-man wrecking crew!`,
		COST:   5,
		HP:     generateHp(2000),
		DPS:    []int{84, 92, 101, 111, 122, 134, 147, 162, 177, 195},
		DAM:    generateDam(126),
		HSPD:   1.5,
		TGTS:   BUILDINGS,
		SPD:    SLOW,
		RNG:    MELEE,
		DTIME:  1,
	})
	MUSKETEER = NewCard(map[Attribute]interface{}{
		NAME:   "Musketeer",
		ARENA:  ARENA_0,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.`,
		COST:   4,
		HP:     generateHp(340),
		DPS:    []int{90, 100, 110, 120, 132, 145, 160, 175, 192, 211},
		DAM:    generateDam(100),
		HSPD:   1.1,
		TGTS:   AIR_AND_GROUND,
		SPD:    MEDIUM,
		RNG:    6.5,
		DTIME:  1,
	})
	MINI_PEKKA = NewCard(map[Attribute]interface{}{
		NAME:   "Mini P.E.K.K.A",
		ARENA:  ARENA_0,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `The arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.`,
		COST:   4,
		HP:     generateHp(600),
		DPS:    []int{180, 198, 218, 240, 263, 288, 317, 348, 382, 420},
		DAM:    generateDam(325),
		HSPD:   1.8,
		TGTS:   GROUND,
		SPD:    FAST,
		RNG:    MELEE,
		DTIME:  1,
	})
	VALKYRIE = NewCard(map[Attribute]interface{}{
		NAME:   "Valkyrie",
		ARENA:  ARENA_1,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.`,
		COST:   4,
		HP:     generateHp(880),
		DPS:    []int{80, 88, 96, 106, 116, 128, 140, 154, 169, 186},
		DAM:    generateDam(120),
		HSPD:   1.5,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    MELEE,
		DTIME:  1,
	})
	HOG_RIDER = NewCard(map[Attribute]interface{}{
		NAME:   "Hog Rider",
		ARENA:  ARENA_4,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the arena doors.`,
		COST:   4,
		HP:     generateHp(800),
		DPS:    []int{106, 117, 128, 141, 155, 170, 187, 205, 226, 248},
		DAM:    generateDam(160),
		HSPD:   1.5,
		TGTS:   BUILDINGS,
		SPD:    VERY_FAST,
		RNG:    MELEE,
		DTIME:  1,
	})
	WIZARD = NewCard(map[Attribute]interface{}{
		NAME:   "Wizard",
		ARENA:  ARENA_5,
		RARITY: RARE,
		TYPE:   TROOP,
		DESC:   `The most awesome man to ever set foot in the arena, the Wizard will blow you away with his handsomeness... and/or fireballs.`,
		COST:   5,
		HP:     generateHp(340),
		DPS:    []int{76, 84, 92, 101, 111, 122, 134, 147, 161, 177},
		ADAM:   generateDam(130),
		HSPD:   1.7,
		TGTS:   AIR_AND_GROUND,
		SPD:    MEDIUM,
		RNG:    5.5,
		DTIME:  1,
	})

	// Epic
	WITCH = NewCard(map[Attribute]interface{}{
		NAME:   "Witch",
		ARENA:  ARENA_0,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `Summons skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.`,
		COST:   5,
		HP:     generateHp(500),
		DPS:    []int{54, 58, 64, 70, 78, 85, 94, 104},
		ADAM:   generateDam(38),
		SKE_LV: []int{6, 7, 8, 9, 10, 11, 12, 13},
		SSPD:   7.5,
		HSPD:   0.7,
		TGTS:   AIR_AND_GROUND,
		SPD:    MEDIUM,
		RNG:    5.5,
		DTIME:  1,
	})
	SKELETON_ARMY = NewCard(map[Attribute]interface{}{
		NAME:   "Skeleton Army",
		ARENA:  ARENA_0,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `Summons an army of skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.`,
		COST:   4,
		HP:     generateHp(30),
		DPS:    V30[0:8:8],
		DAM:    generateDam(30),
		HSPD:   1,
		TGTS:   GROUND,
		SPD:    FAST,
		RNG:    MELEE,
		DTIME:  1,
		COUNT:  20,
	})
	BABY_DRAGON = NewCard(map[Attribute]interface{}{
		NAME:   "Baby Dragon",
		ARENA:  ARENA_0,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `Flying troop that deals area damage. Baby dragons hatch cute, hungry, and ready for a barbeque.`,
		COST:   4,
		HP:     generateHp(800),
		DPS:    []int{55, 61, 67, 73, 81, 88, 97, 107},
		ADAM:   generateDam(100),
		HSPD:   1.8,
		TGTS:   AIR_AND_GROUND,
		SPD:    FAST,
		RNG:    3.5,
		DTIME:  1,
	})
	PRINCE = NewCard(map[Attribute]interface{}{
		NAME:   "Prince",
		ARENA:  ARENA_0,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Does 2x damage once he gets charging.`,
		COST:   5,
		HP:     generateHp(1100),
		DPS:    []int{146, 161, 177, 194, 214, 234, 258, 282},
		DAM:    generateDam(220),
		HSPD:   1.5,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    2.5,
		DTIME:  1,
	})
	GIANT_SKELETON = NewCard(map[Attribute]interface{}{
		NAME:   "Giant Skeleton",
		ARENA:  ARENA_2,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.`,
		COST:   6,
		HP:     generateHp(2000),
		DPS:    []int{66, 73, 80, 88, 97, 106, 117, 128},
		DAM:    generateDam(100),
		DDAM:   generateDam(720),
		HSPD:   1.5,
		TGTS:   GROUND,
		SPD:    MEDIUM,
		RNG:    MELEE,
		DTIME:  1,
	})
	BALLOON = NewCard(map[Attribute]interface{}{
		NAME:   "Balloon",
		ARENA:  ARENA_2,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.`,
		COST:   5,
		HP:     generateHp(1050),
		DPS:    []int{200, 220, 242, 266, 292, 320, 352, 386},
		DAM:    generateDam(600),
		DDAM:   generateDam(100),
		HSPD:   3,
		TGTS:   BUILDINGS,
		SPD:    MEDIUM,
		RNG:    MELEE,
		DTIME:  1,
	})
	PEKKA = NewCard(map[Attribute]interface{}{
		NAME:   "P.E.K.K.A",
		ARENA:  ARENA_4,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `A heavily armored, slow melee fighter. Swings from the hip but packs a huge punch.`,
		COST:   7,
		HP:     generateHp(2600),
		DPS:    []int{250, 275, 302, 332, 365, 400, 440, 482},
		DAM:    generateDam(450),
		HSPD:   1.8,
		TGTS:   GROUND,
		SPD:    SLOW,
		RNG:    MELEE,
		DTIME:  3,
	})
	GOLEM = NewCard(map[Attribute]interface{}{
		NAME:   "Golem",
		ARENA:  ARENA_6,
		RARITY: EPIC,
		TYPE:   TROOP,
		DESC:   `Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!`,
		COST:   8,
		HP:     generateHp(3000),
		DPS:    []int{74, 81, 90, 98, 108, 118, 130, 143},
		DAM:    generateDam(186),
		DDAM:   generateDam(186),
		HSPD:   2.5,
		TGTS:   BUILDINGS,
		SPD:    SLOW,
		RNG:    MELEE,
		DTIME:  3,
	})
)
