package lib

var (
	// Common
	CANNON = Card{
		NAME:   "Cannon",
		ARENA:  ARENA_3,
		RARITY: COMMON,
		TYPE:   BUILDING,
		DESC:   `Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops.`,
		COST:   3,
		HP:     V450[0:12:12],
		DPS:    []int{75, 82, 90, 98, 108, 120, X, X, X, X, X, 210},
		DAM:    []int{60, 66, 72, 79, 87, 96, X, X, X, X, X, 168},
		HSPD:   0.8,
		TGTS:   GROUND,
		RNG:    6,
		DTIME:  1,
		LTIME:  30,
	}
	TESLA = Card{
		NAME:   "Tesla",
		ARENA:  ARENA_4,
		RARITY: COMMON,
		TYPE:   BUILDING,
		DESC:   `Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded.`,
		COST:   4,
		HP:     V400[0:12:12],
		DPS:    []int{80, X, X, X, X, X, X, X, X, X, X, X},
		DAM:    []int{64, X, X, X, 93, 102, 112, X, X, 149, 163, 179},
		HSPD:   0.8,
		TGTS:   AIR_AND_GROUND,
		RNG:    6,
		DTIME:  1,
		LTIME:  40,
	}
	MORTAR = Card{
		NAME:   "Mortar",
		ARENA:  ARENA_6,
		RARITY: COMMON,
		TYPE:   BUILDING,
		DESC:   `Defensive building with a long range. Shoots exploding shells that deal area damage. Cannot shoot at targets that get very close!`,
		COST:   4,
		HP:     V600[0:12:12],
		DPS:    []int{24, X, X, X, X, X, X, X, X, X, X, 67},
		ADAM:   []int{120, X, X, X, X, X, X, X, X, X, X, 337},
		HSPD:   5,
		TGTS:   GROUND,
		RNG:    12,
		DTIME:  3,
		LTIME:  30,
	}

	// Rare
	GOBLIN_HUT = Card{
		NAME:   "Goblin Hut",
		ARENA:  ARENA_1,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `Building that spawns Spear Goblins. But don't look inside. You don't want to see how they are made.`,
		COST:   5,
		HP:     V700[0:10:10],
		SGO_LV: []int{3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
		SSPD:   4.9,
		DTIME:  1,
		LTIME:  60,
	}
	BOMB_TOWER = Card{
		NAME:   "Bomb Tower",
		ARENA:  ARENA_2,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it.`,
		COST:   5,
		HP:     V900[0:10:10],
		DPS:    []int{62, 68, 75, 83, 91, X, X, X, 132, 145},
		ADAM:   V100[0:10:10],
		HSPD:   1.6,
		TGTS:   GROUND,
		RNG:    6.5,
		DTIME:  1,
		LTIME:  60,
	}
	TOMBSTONE = Card{
		NAME:   "Tombstone",
		ARENA:  ARENA_2,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `Troop building that periodically deploys Skeletons to fight the enemy. When destroyed, spawns 4 Skeletons. Creepy!`,
		COST:   3,
		HP:     V200[0:10:10],
		SKE_LV: []int{3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
		SSPD:   2.9,
		DTIME:  1,
		LTIME:  40,
	}
	BARBARIAN_HUT = Card{
		NAME:   "Barbarian Hut",
		ARENA:  ARENA_3,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `Troop building that periodically deploys Barbarians to fight the enemy. Time to make the Barbarians.`,
		COST:   7,
		HP:     V1100[0:10:10],
		BAR_LV: []int{3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
		SSPD:   14,
		DTIME:  1,
		LTIME:  60,
	}
	INFERNO_TOWER = Card{
		NAME:   "Inferno Tower",
		ARENA:  ARENA_6,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!`,
		COST:   5,
		HP:     V800[0:10:10],
		DPSL:   []int{50, 55, 60, 65, X, X, X, 95, 105, 115},
		DPSH:   []int{1000, 1100, 1210, 1330, X, X, X, 1930, 2120, 2330},
		DAML:   []int{20, 22, 24, 26, X, X, X, 38, 42, 46},
		DAMH:   []int{400, 440, 484, 532, X, X, X, 772, 848, 932},
		HSPD:   0.4,
		TGTS:   AIR_AND_GROUND,
		RNG:    6.5,
		DTIME:  1,
		LTIME:  40,
	}
	ELIXIR_COLLECTOR = Card{
		NAME:   "Elixir Collector",
		ARENA:  ARENA_6,
		RARITY: RARE,
		TYPE:   BUILDING,
		DESC:   `You gotta spend Elixir to make Elixir.`,
		COST:   5,
		HP:     V800[0:10:10],
		PSPD:   9.8,
		DTIME:  1,
		LTIME:  70,
	}

	// Epic
	X_BOW = Card{
		NAME:   "X-Bow",
		ARENA:  ARENA_3,
		RARITY: EPIC,
		TYPE:   BUILDING,
		DESC:   `Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the arena...`,
		COST:   6,
		HP:     V850[0:8:8],
		DPS:    []int{66, 73, 80, X, 96, 106, 116, X},
		DAM:    []int{20, 22, 24, X, 29, 32, 35, X},
		HSPD:   0.3,
		TGTS:   GROUND,
		RNG:    12,
		DTIME:  5,
		LTIME:  40,
	}
)
