package card

import (
	"github.com/asukakenji/clash-royale/arena"
	"github.com/asukakenji/clash-royale/attribute"
	"github.com/asukakenji/clash-royale/lib"
	"github.com/asukakenji/clash-royale/rarity"
	"github.com/asukakenji/clash-royale/speed"
	"github.com/asukakenji/clash-royale/targets"
	"github.com/asukakenji/clash-royale/types"
)

var (
	// --- Common Troops ---
	KNIGHT = newCard(0, map[attribute.Attribute]interface{}{
		attribute.Name:    "Knight",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.`,
		attribute.Elixir:  3,
		attribute.BaseHP:  600,
		attribute.DPS:     []int{68, 74, 81, 90, 99, 109, 120, 130, 144, 158, 174, 190},
		attribute.BaseDam: 75,
		attribute.HSpeed:  1.1,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Medium,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
	})
	ARCHERS = newCard(1, map[attribute.Attribute]interface{}{
		attribute.Name:    "Archers",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `A pair of unarmored ranged attackers. They'll help you with ground and air unit attacks, but you're on your own with coloring your hair.`,
		attribute.Elixir:  3,
		attribute.BaseHP:  125,
		attribute.DPS:     []int{33, 36, 40, 44, 48, 53, 58, 64, 70, 77, 85, 93},
		attribute.BaseDam: 40,
		attribute.HSpeed:  1.2,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.Medium,
		attribute.Range:   5.5,
		attribute.DTime:   1,
		attribute.Count:   2,
	})
	BOMBER = newCard(2, map[attribute.Attribute]interface{}{
		attribute.Name:     "Bomber",
		attribute.Arena:    arena.Arena0,
		attribute.Rarity:   rarity.Common,
		attribute.Type:     types.Troop,
		attribute.Desc:     `Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.`,
		attribute.Elixir:   3,
		attribute.BaseHP:   150,
		attribute.DPS:      []int{52, 57, 63, 70, 76, 84, 92, 101, 111, 122, 134, 147},
		attribute.BaseADam: 100,
		attribute.HSpeed:   1.9,
		attribute.Targets:  targets.Ground,
		attribute.Speed:    speed.Medium,
		attribute.Range:    5,
		attribute.DTime:    1,
	})
	GOBLINS = newCard(10, map[attribute.Attribute]interface{}{
		attribute.Name:    "Goblins",
		attribute.Arena:   arena.Arena1,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Three fast, unarmored melee attackers. Small, fast, green and mean!`,
		attribute.Elixir:  2,
		attribute.BaseHP:  80,
		attribute.DPS:     []int{45, 50, 54, 60, 66, 72, 80, 87, 96, 105, 116, 127},
		attribute.BaseDam: 50,
		attribute.HSpeed:  1.1,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.VeryFast,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
		attribute.Count:   3,
	})
	SPEAR_GOBLINS = newCard(11, map[attribute.Attribute]interface{}{
		attribute.Name:    "Spear Goblins",
		attribute.Arena:   arena.Arena1,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Three unarmored ranged attackers. Who the heck taught these guys to throw spears!?! Who thought that was a good idea?!`,
		attribute.Elixir:  2,
		attribute.BaseHP:  52,
		attribute.DPS:     []int{18, 20, 22, 23, 26, 29, 32, 35, 38, 42, 46, 51},
		attribute.BaseDam: 24,
		attribute.HSpeed:  1.3,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.VeryFast,
		attribute.Range:   5.5,
		attribute.DTime:   1,
		attribute.Count:   3,
	})
	SKELETONS = newCard(20, map[attribute.Attribute]interface{}{
		attribute.Name:    "Skeletons",
		attribute.Arena:   arena.Arena2,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Four fast, very weak melee fighters. Swarm your enemies with this pile of bones!`,
		attribute.Elixir:  1,
		attribute.BaseHP:  30,
		attribute.DPS:     lib.V30[0:12:12],
		attribute.BaseDam: 30,
		attribute.HSpeed:  1,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Fast,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
		attribute.Count:   4,
	})
	MINIONS = newCard(21, map[attribute.Attribute]interface{}{
		attribute.Name:    "Minions",
		attribute.Arena:   arena.Arena2,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!`,
		attribute.Elixir:  3,
		attribute.BaseHP:  90,
		attribute.DPS:     lib.V40[0:12:12],
		attribute.BaseDam: 40,
		attribute.HSpeed:  1,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.Fast,
		attribute.Range:   2.5,
		attribute.DTime:   1,
		attribute.Count:   3,
	})
	BARBARIANS = newCard(30, map[attribute.Attribute]interface{}{
		attribute.Name:    "Barbarians",
		attribute.Arena:   arena.Arena3,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `A horde of melee attackers with mean mustaches and even meaner tempers.`,
		attribute.Elixir:  5,
		attribute.BaseHP:  300,
		attribute.DPS:     []int{50, 54, 60, 66, 72, 80, 88, 96, 106, 116, 128, 140},
		attribute.BaseDam: 75,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Medium,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
		attribute.Count:   4,
	})
	MINION_HORDE = newCard(40, map[attribute.Attribute]interface{}{
		attribute.Name:    "Minion Horde",
		attribute.Arena:   arena.Arena4,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Six fast, unarmored flying attackers. Three's a crowd, six is a horde!`,
		attribute.Elixir:  5,
		attribute.BaseHP:  90,
		attribute.DPS:     lib.V40[0:12:12],
		attribute.BaseDam: 40,
		attribute.HSpeed:  1,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.Fast,
		attribute.Range:   2.5,
		attribute.DTime:   1,
		attribute.Count:   6,
	})
	ROYALE_GIANT = newCard(70, map[attribute.Attribute]interface{}{
		attribute.Name:    "Royale Giant",
		attribute.Arena:   arena.Arena7,
		attribute.Rarity:  rarity.Common,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Sighting his massive cannon at enemy buildings, the Royal Giant comes in like a wrecking ball.`,
		attribute.Elixir:  6,
		attribute.BaseHP:  1200,
		attribute.DPS:     []int{52, 56, 62, 68, 75, 83, 91, 100, 110, 122, 133, 146},
		attribute.BaseDam: 78,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Buildings,
		attribute.Speed:   speed.Slow,
		attribute.Range:   6,
		attribute.DTime:   1,
	})

	// --- Rare Troops ---
	GIANT = newCard(100, map[attribute.Attribute]interface{}{
		attribute.Name:    "Giant",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Slow but durable, only attacks buildings. A real one-man wrecking crew!`,
		attribute.Elixir:  5,
		attribute.BaseHP:  2000,
		attribute.DPS:     []int{84, 92, 101, 111, 122, 134, 147, 162, 177, 195},
		attribute.BaseDam: 126,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Buildings,
		attribute.Speed:   speed.Slow,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
	})
	MUSKETEER = newCard(101, map[attribute.Attribute]interface{}{
		attribute.Name:    "Musketeer",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.`,
		attribute.Elixir:  4,
		attribute.BaseHP:  340,
		attribute.DPS:     []int{90, 100, 110, 120, 132, 145, 160, 175, 192, 211},
		attribute.BaseDam: 100,
		attribute.HSpeed:  1.1,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.Medium,
		attribute.Range:   6.5,
		attribute.DTime:   1,
	})
	MINI_PEKKA = newCard(102, map[attribute.Attribute]interface{}{
		attribute.Name:    "Mini P.E.K.K.A",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `The arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.`,
		attribute.Elixir:  4,
		attribute.BaseHP:  600,
		attribute.DPS:     []int{180, 198, 218, 240, 263, 288, 317, 348, 382, 420},
		attribute.BaseDam: 325,
		attribute.HSpeed:  1.8,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Fast,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
	})
	VALKYRIE = newCard(110, map[attribute.Attribute]interface{}{
		attribute.Name:    "Valkyrie",
		attribute.Arena:   arena.Arena1,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.`,
		attribute.Elixir:  4,
		attribute.BaseHP:  880,
		attribute.DPS:     []int{80, 88, 96, 106, 116, 128, 140, 154, 169, 186},
		attribute.BaseDam: 120,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Medium,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
	})
	HOG_RIDER = newCard(140, map[attribute.Attribute]interface{}{
		attribute.Name:    "Hog Rider",
		attribute.Arena:   arena.Arena4,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the arena doors.`,
		attribute.Elixir:  4,
		attribute.BaseHP:  800,
		attribute.DPS:     []int{106, 117, 128, 141, 155, 170, 187, 205, 226, 248},
		attribute.BaseDam: 160,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Buildings,
		attribute.Speed:   speed.VeryFast,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
	})
	WIZARD = newCard(150, map[attribute.Attribute]interface{}{
		attribute.Name:     "Wizard",
		attribute.Arena:    arena.Arena5,
		attribute.Rarity:   rarity.Rare,
		attribute.Type:     types.Troop,
		attribute.Desc:     `The most awesome man to ever set foot in the arena, the Wizard will blow you away with his handsomeness... and/or fireballs.`,
		attribute.Elixir:   5,
		attribute.BaseHP:   340,
		attribute.DPS:      []int{76, 84, 92, 101, 111, 122, 134, 147, 161, 177},
		attribute.BaseADam: 130,
		attribute.HSpeed:   1.7,
		attribute.Targets:  targets.AirAndGround,
		attribute.Speed:    speed.Medium,
		attribute.Range:    5.5,
		attribute.DTime:    1,
	})
	THREE_MUSKETEERS = newCard(170, map[attribute.Attribute]interface{}{
		attribute.Name:    "Three Musketeers",
		attribute.Arena:   arena.Arena7,
		attribute.Rarity:  rarity.Rare,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Trio of powerful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!`,
		attribute.Elixir:  9,
		attribute.BaseHP:  340,
		attribute.DPS:     []int{90, 100, 110, 120, 132, 145, 160, 175, 192, 211},
		attribute.BaseDam: 100,
		attribute.HSpeed:  1.1,
		attribute.Targets: targets.AirAndGround,
		attribute.Speed:   speed.Medium,
		attribute.Range:   6.5,
		attribute.DTime:   1,
		attribute.Count:   3,
	})

	// --- Epic Troops ---
	WITCH = newCard(200, map[attribute.Attribute]interface{}{
		attribute.Name:      "Witch",
		attribute.Arena:     arena.Arena0,
		attribute.Rarity:    rarity.Epic,
		attribute.Type:      types.Troop,
		attribute.Desc:      `Summons skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.`,
		attribute.Elixir:    5,
		attribute.BaseHP:    500,
		attribute.DPS:       []int{54, 58, 64, 70, 78, 85, 94, 104},
		attribute.BaseADam:  38,
		attribute.BaseSkeLV: 6,
		attribute.SSpeed:    7.5,
		attribute.HSpeed:    0.7,
		attribute.Targets:   targets.AirAndGround,
		attribute.Speed:     speed.Medium,
		attribute.Range:     5.5,
		attribute.DTime:     1,
	})
	SKELETON_ARMY = newCard(201, map[attribute.Attribute]interface{}{
		attribute.Name:    "Skeleton Army",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Epic,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Summons an army of skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.`,
		attribute.Elixir:  4,
		attribute.BaseHP:  30,
		attribute.DPS:     lib.V30[0:8:8],
		attribute.BaseDam: 30,
		attribute.HSpeed:  1,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Fast,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   1,
		attribute.Count:   20,
	})
	BABY_DRAGON = newCard(202, map[attribute.Attribute]interface{}{
		attribute.Name:     "Baby Dragon",
		attribute.Arena:    arena.Arena0,
		attribute.Rarity:   rarity.Epic,
		attribute.Type:     types.Troop,
		attribute.Desc:     `Flying troop that deals area damage. Baby dragons hatch cute, hungry, and ready for a barbeque.`,
		attribute.Elixir:   4,
		attribute.BaseHP:   800,
		attribute.DPS:      []int{55, 61, 67, 73, 81, 88, 97, 107},
		attribute.BaseADam: 100,
		attribute.HSpeed:   1.8,
		attribute.Targets:  targets.AirAndGround,
		attribute.Speed:    speed.Fast,
		attribute.Range:    3.5,
		attribute.DTime:    1,
	})
	PRINCE = newCard(203, map[attribute.Attribute]interface{}{
		attribute.Name:    "Prince",
		attribute.Arena:   arena.Arena0,
		attribute.Rarity:  rarity.Epic,
		attribute.Type:    types.Troop,
		attribute.Desc:    `Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Does 2x damage once he gets charging.`,
		attribute.Elixir:  5,
		attribute.BaseHP:  1100,
		attribute.DPS:     []int{146, 161, 177, 194, 214, 234, 258, 282},
		attribute.BaseDam: 220,
		attribute.HSpeed:  1.5,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Medium,
		attribute.Range:   2.5,
		attribute.DTime:   1,
	})
	GIANT_SKELETON = newCard(220, map[attribute.Attribute]interface{}{
		attribute.Name:     "Giant Skeleton",
		attribute.Arena:    arena.Arena2,
		attribute.Rarity:   rarity.Epic,
		attribute.Type:     types.Troop,
		attribute.Desc:     `The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.`,
		attribute.Elixir:   6,
		attribute.BaseHP:   2000,
		attribute.DPS:      []int{66, 73, 80, 88, 97, 106, 117, 128},
		attribute.BaseDam:  100,
		attribute.BaseDDam: 720,
		attribute.HSpeed:   1.5,
		attribute.Targets:  targets.Ground,
		attribute.Speed:    speed.Medium,
		attribute.Range:    lib.MELEE,
		attribute.DTime:    1,
	})
	BALLOON = newCard(221, map[attribute.Attribute]interface{}{
		attribute.Name:     "Balloon",
		attribute.Arena:    arena.Arena2,
		attribute.Rarity:   rarity.Epic,
		attribute.Type:     types.Troop,
		attribute.Desc:     `As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.`,
		attribute.Elixir:   5,
		attribute.BaseHP:   1050,
		attribute.DPS:      []int{200, 220, 242, 266, 292, 320, 352, 386},
		attribute.BaseDam:  600,
		attribute.BaseDDam: 100,
		attribute.HSpeed:   3,
		attribute.Targets:  targets.Buildings,
		attribute.Speed:    speed.Medium,
		attribute.Range:    lib.MELEE,
		attribute.DTime:    1,
	})
	PEKKA = newCard(240, map[attribute.Attribute]interface{}{
		attribute.Name:    "P.E.K.K.A",
		attribute.Arena:   arena.Arena4,
		attribute.Rarity:  rarity.Epic,
		attribute.Type:    types.Troop,
		attribute.Desc:    `A heavily armored, slow melee fighter. Swings from the hip but packs a huge punch.`,
		attribute.Elixir:  7,
		attribute.BaseHP:  2600,
		attribute.DPS:     []int{250, 275, 302, 332, 365, 400, 440, 482},
		attribute.BaseDam: 450,
		attribute.HSpeed:  1.8,
		attribute.Targets: targets.Ground,
		attribute.Speed:   speed.Slow,
		attribute.Range:   lib.MELEE,
		attribute.DTime:   3,
	})
	GOLEM = newCard(260, map[attribute.Attribute]interface{}{
		attribute.Name:     "Golem",
		attribute.Arena:    arena.Arena6,
		attribute.Rarity:   rarity.Epic,
		attribute.Type:     types.Troop,
		attribute.Desc:     `Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!`,
		attribute.Elixir:   8,
		attribute.BaseHP:   3000,
		attribute.DPS:      []int{74, 81, 90, 98, 108, 118, 130, 143},
		attribute.BaseDam:  186,
		attribute.BaseDDam: 186,
		attribute.HSpeed:   2.5,
		attribute.Targets:  targets.Buildings,
		attribute.Speed:    speed.Slow,
		attribute.Range:    lib.MELEE,
		attribute.DTime:    3,
	})
	DARK_PRINCE = newCard(270, map[attribute.Attribute]interface{}{
		attribute.Name:     "Dark Prince",
		attribute.Arena:    arena.Arena7,
		attribute.Rarity:   rarity.Epic,
		attribute.Type:     types.Troop,
		attribute.Desc:     `Dealing area damage with each swing and double after charging, the Dark Prince is a formidable fighter. To harm his squishy core, break his shield first.`,
		attribute.Elixir:   4,
		attribute.BaseHP:   700,
		attribute.BaseSHP:  200,
		attribute.DPS:      []int{83, 91, 100, 110, 121, 133, 146, 159},
		attribute.BaseADam: 125,
		attribute.HSpeed:   1.5,
		attribute.Targets:  targets.Ground,
		attribute.Speed:    speed.Medium,
		attribute.Range:    lib.MELEE,
		attribute.DTime:    1,
	})

	// --- Legendary Troops ---
	ICE_WIZARD = newCard(350, map[attribute.Attribute]interface{}{
		attribute.Name:     "Ice Wizard",
		attribute.Arena:    arena.Arena5,
		attribute.Rarity:   rarity.Legendary,
		attribute.Type:     types.Troop,
		attribute.Desc:     `This chill caster hails from the far North. He shoots ice shards at enemies, slowing down their movement and attack speed.`,
		attribute.Elixir:   3,
		attribute.BaseHP:   700,
		attribute.DPS:      []int{42, 46, 50, 55, 60, 67},
		attribute.BaseADam: 63,
		attribute.HSpeed:   1.5,
		attribute.Targets:  targets.AirAndGround,
		attribute.Speed:    speed.Medium,
		attribute.Range:    6,
		attribute.DTime:    1,
	})
	PRINCESS = newCard(370, map[attribute.Attribute]interface{}{
		attribute.Name:     "Princess",
		attribute.Arena:    arena.Arena7,
		attribute.Rarity:   rarity.Legendary,
		attribute.Type:     types.Troop,
		attribute.Desc:     `Shoots a volley of flaming arrows halfway across the Arena. The Princess is afraid of germs, so keep the rabble away from her!`,
		attribute.Elixir:   3,
		attribute.BaseHP:   216,
		attribute.DPS:      []int{46, 51, 56, 62, 68, 74},
		attribute.BaseADam: 140,
		attribute.HSpeed:   3,
		attribute.Targets:  targets.AirAndGround,
		attribute.Speed:    speed.Medium,
		attribute.Range:    9.5,
		attribute.DTime:    1,
	})
)
