package card

import (
	"github.com/asukakenji/clash-royale/arena"
	"github.com/asukakenji/clash-royale/attribute"
	"github.com/asukakenji/clash-royale/lib"
	"github.com/asukakenji/clash-royale/rarity"
	"github.com/asukakenji/clash-royale/speed"
	"github.com/asukakenji/clash-royale/targets"
	"github.com/asukakenji/clash-royale/types"
)

var (
	// --- Common Troops ---
	KNIGHT = newCard(0, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Knight",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.`,
		attribute.COST:     3,
		attribute.BASE_HP:  600,
		attribute.DPS:      []int{68, 74, 81, 90, 99, 109, 120, 130, 144, 158, 174, 190},
		attribute.BASE_DAM: 75,
		attribute.HSPD:     1.1,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
	})
	ARCHERS = newCard(1, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Archers",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `A pair of unarmored ranged attackers. They'll help you with ground and air unit attacks, but you're on your own with coloring your hair.`,
		attribute.COST:     3,
		attribute.BASE_HP:  125,
		attribute.DPS:      []int{33, 36, 40, 44, 48, 53, 58, 64, 70, 77, 85, 93},
		attribute.BASE_DAM: 40,
		attribute.HSPD:     1.2,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      5.5,
		attribute.DTIME:    1,
		attribute.COUNT:    2,
	})
	BOMBER = newCard(2, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Bomber",
		attribute.ARENA:     arena.ARENA_0,
		attribute.RARITY:    rarity.COMMON,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.`,
		attribute.COST:      3,
		attribute.BASE_HP:   150,
		attribute.DPS:       []int{52, 57, 63, 70, 76, 84, 92, 101, 111, 122, 134, 147},
		attribute.BASE_ADAM: 100,
		attribute.HSPD:      1.9,
		attribute.TGTS:      targets.GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       5,
		attribute.DTIME:     1,
	})
	GOBLINS = newCard(10, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Goblins",
		attribute.ARENA:    arena.ARENA_1,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Three fast, unarmored melee attackers. Small, fast, green and mean!`,
		attribute.COST:     2,
		attribute.BASE_HP:  80,
		attribute.DPS:      []int{45, 50, 54, 60, 66, 72, 80, 87, 96, 105, 116, 127},
		attribute.BASE_DAM: 50,
		attribute.HSPD:     1.1,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.VERY_FAST,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
		attribute.COUNT:    3,
	})
	SPEAR_GOBLINS = newCard(11, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Spear Goblins",
		attribute.ARENA:    arena.ARENA_1,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Three unarmored ranged attackers. Who the heck taught these guys to throw spears!?! Who thought that was a good idea?!`,
		attribute.COST:     2,
		attribute.BASE_HP:  52,
		attribute.DPS:      []int{18, 20, 22, 23, 26, 29, 32, 35, 38, 42, 46, 51},
		attribute.BASE_DAM: 24,
		attribute.HSPD:     1.3,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.VERY_FAST,
		attribute.RNG:      5.5,
		attribute.DTIME:    1,
		attribute.COUNT:    3,
	})
	SKELETONS = newCard(20, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Skeletons",
		attribute.ARENA:    arena.ARENA_2,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Four fast, very weak melee fighters. Swarm your enemies with this pile of bones!`,
		attribute.COST:     1,
		attribute.BASE_HP:  30,
		attribute.DPS:      lib.V30[0:12:12],
		attribute.BASE_DAM: 30,
		attribute.HSPD:     1,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.FAST,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
		attribute.COUNT:    4,
	})
	MINIONS = newCard(21, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Minions",
		attribute.ARENA:    arena.ARENA_2,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!`,
		attribute.COST:     3,
		attribute.BASE_HP:  90,
		attribute.DPS:      lib.V40[0:12:12],
		attribute.BASE_DAM: 40,
		attribute.HSPD:     1,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.FAST,
		attribute.RNG:      2.5,
		attribute.DTIME:    1,
		attribute.COUNT:    3,
	})
	BARBARIANS = newCard(30, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Barbarians",
		attribute.ARENA:    arena.ARENA_3,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `A horde of melee attackers with mean mustaches and even meaner tempers.`,
		attribute.COST:     5,
		attribute.BASE_HP:  300,
		attribute.DPS:      []int{50, 54, 60, 66, 72, 80, 88, 96, 106, 116, 128, 140},
		attribute.BASE_DAM: 75,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
		attribute.COUNT:    4,
	})
	MINION_HORDE = newCard(40, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Minion Horde",
		attribute.ARENA:    arena.ARENA_4,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Six fast, unarmored flying attackers. Three's a crowd, six is a horde!`,
		attribute.COST:     5,
		attribute.BASE_HP:  90,
		attribute.DPS:      lib.V40[0:12:12],
		attribute.BASE_DAM: 40,
		attribute.HSPD:     1,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.FAST,
		attribute.RNG:      2.5,
		attribute.DTIME:    1,
		attribute.COUNT:    6,
	})
	ROYALE_GIANT = newCard(70, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Royale Giant",
		attribute.ARENA:    arena.ARENA_7,
		attribute.RARITY:   rarity.COMMON,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Sighting his massive cannon at enemy buildings, the Royal Giant comes in like a wrecking ball.`,
		attribute.COST:     6,
		attribute.BASE_HP:  1200,
		attribute.DPS:      []int{52, 56, 62, 68, 75, 83, 91, 100, 110, 122, 133, 146},
		attribute.BASE_DAM: 78,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.BUILDINGS,
		attribute.SPD:      speed.SLOW,
		attribute.RNG:      6,
		attribute.DTIME:    1,
	})

	// --- Rare Troops ---
	GIANT = newCard(100, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Giant",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Slow but durable, only attacks buildings. A real one-man wrecking crew!`,
		attribute.COST:     5,
		attribute.BASE_HP:  2000,
		attribute.DPS:      []int{84, 92, 101, 111, 122, 134, 147, 162, 177, 195},
		attribute.BASE_DAM: 126,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.BUILDINGS,
		attribute.SPD:      speed.SLOW,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
	})
	MUSKETEER = newCard(101, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Musketeer",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.`,
		attribute.COST:     4,
		attribute.BASE_HP:  340,
		attribute.DPS:      []int{90, 100, 110, 120, 132, 145, 160, 175, 192, 211},
		attribute.BASE_DAM: 100,
		attribute.HSPD:     1.1,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      6.5,
		attribute.DTIME:    1,
	})
	MINI_PEKKA = newCard(102, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Mini P.E.K.K.A",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `The arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.`,
		attribute.COST:     4,
		attribute.BASE_HP:  600,
		attribute.DPS:      []int{180, 198, 218, 240, 263, 288, 317, 348, 382, 420},
		attribute.BASE_DAM: 325,
		attribute.HSPD:     1.8,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.FAST,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
	})
	VALKYRIE = newCard(110, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Valkyrie",
		attribute.ARENA:    arena.ARENA_1,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.`,
		attribute.COST:     4,
		attribute.BASE_HP:  880,
		attribute.DPS:      []int{80, 88, 96, 106, 116, 128, 140, 154, 169, 186},
		attribute.BASE_DAM: 120,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
	})
	HOG_RIDER = newCard(140, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Hog Rider",
		attribute.ARENA:    arena.ARENA_4,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the arena doors.`,
		attribute.COST:     4,
		attribute.BASE_HP:  800,
		attribute.DPS:      []int{106, 117, 128, 141, 155, 170, 187, 205, 226, 248},
		attribute.BASE_DAM: 160,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.BUILDINGS,
		attribute.SPD:      speed.VERY_FAST,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
	})
	WIZARD = newCard(150, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Wizard",
		attribute.ARENA:     arena.ARENA_5,
		attribute.RARITY:    rarity.RARE,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `The most awesome man to ever set foot in the arena, the Wizard will blow you away with his handsomeness... and/or fireballs.`,
		attribute.COST:      5,
		attribute.BASE_HP:   340,
		attribute.DPS:       []int{76, 84, 92, 101, 111, 122, 134, 147, 161, 177},
		attribute.BASE_ADAM: 130,
		attribute.HSPD:      1.7,
		attribute.TGTS:      targets.AIR_AND_GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       5.5,
		attribute.DTIME:     1,
	})
	THREE_MUSKETEERS = newCard(170, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Three Musketeers",
		attribute.ARENA:    arena.ARENA_7,
		attribute.RARITY:   rarity.RARE,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Trio of powerful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!`,
		attribute.COST:     9,
		attribute.BASE_HP:  340,
		attribute.DPS:      []int{90, 100, 110, 120, 132, 145, 160, 175, 192, 211},
		attribute.BASE_DAM: 100,
		attribute.HSPD:     1.1,
		attribute.TGTS:     targets.AIR_AND_GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      6.5,
		attribute.DTIME:    1,
		attribute.COUNT:    3,
	})

	// --- Epic Troops ---
	WITCH = newCard(200, map[attribute.Attribute]interface{}{
		attribute.NAME:        "Witch",
		attribute.ARENA:       arena.ARENA_0,
		attribute.RARITY:      rarity.EPIC,
		attribute.TYPE:        types.TROOP,
		attribute.DESC:        `Summons skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.`,
		attribute.COST:        5,
		attribute.BASE_HP:     500,
		attribute.DPS:         []int{54, 58, 64, 70, 78, 85, 94, 104},
		attribute.BASE_ADAM:   38,
		attribute.BASE_SKE_LV: 6,
		attribute.SSPD:        7.5,
		attribute.HSPD:        0.7,
		attribute.TGTS:        targets.AIR_AND_GROUND,
		attribute.SPD:         speed.MEDIUM,
		attribute.RNG:         5.5,
		attribute.DTIME:       1,
	})
	SKELETON_ARMY = newCard(201, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Skeleton Army",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.EPIC,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Summons an army of skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.`,
		attribute.COST:     4,
		attribute.BASE_HP:  30,
		attribute.DPS:      lib.V30[0:8:8],
		attribute.BASE_DAM: 30,
		attribute.HSPD:     1,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.FAST,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    1,
		attribute.COUNT:    20,
	})
	BABY_DRAGON = newCard(202, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Baby Dragon",
		attribute.ARENA:     arena.ARENA_0,
		attribute.RARITY:    rarity.EPIC,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `Flying troop that deals area damage. Baby dragons hatch cute, hungry, and ready for a barbeque.`,
		attribute.COST:      4,
		attribute.BASE_HP:   800,
		attribute.DPS:       []int{55, 61, 67, 73, 81, 88, 97, 107},
		attribute.BASE_ADAM: 100,
		attribute.HSPD:      1.8,
		attribute.TGTS:      targets.AIR_AND_GROUND,
		attribute.SPD:       speed.FAST,
		attribute.RNG:       3.5,
		attribute.DTIME:     1,
	})
	PRINCE = newCard(203, map[attribute.Attribute]interface{}{
		attribute.NAME:     "Prince",
		attribute.ARENA:    arena.ARENA_0,
		attribute.RARITY:   rarity.EPIC,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Does 2x damage once he gets charging.`,
		attribute.COST:     5,
		attribute.BASE_HP:  1100,
		attribute.DPS:      []int{146, 161, 177, 194, 214, 234, 258, 282},
		attribute.BASE_DAM: 220,
		attribute.HSPD:     1.5,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.MEDIUM,
		attribute.RNG:      2.5,
		attribute.DTIME:    1,
	})
	GIANT_SKELETON = newCard(220, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Giant Skeleton",
		attribute.ARENA:     arena.ARENA_2,
		attribute.RARITY:    rarity.EPIC,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.`,
		attribute.COST:      6,
		attribute.BASE_HP:   2000,
		attribute.DPS:       []int{66, 73, 80, 88, 97, 106, 117, 128},
		attribute.BASE_DAM:  100,
		attribute.BASE_DDAM: 720,
		attribute.HSPD:      1.5,
		attribute.TGTS:      targets.GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       lib.MELEE,
		attribute.DTIME:     1,
	})
	BALLOON = newCard(221, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Balloon",
		attribute.ARENA:     arena.ARENA_2,
		attribute.RARITY:    rarity.EPIC,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.`,
		attribute.COST:      5,
		attribute.BASE_HP:   1050,
		attribute.DPS:       []int{200, 220, 242, 266, 292, 320, 352, 386},
		attribute.BASE_DAM:  600,
		attribute.BASE_DDAM: 100,
		attribute.HSPD:      3,
		attribute.TGTS:      targets.BUILDINGS,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       lib.MELEE,
		attribute.DTIME:     1,
	})
	PEKKA = newCard(240, map[attribute.Attribute]interface{}{
		attribute.NAME:     "P.E.K.K.A",
		attribute.ARENA:    arena.ARENA_4,
		attribute.RARITY:   rarity.EPIC,
		attribute.TYPE:     types.TROOP,
		attribute.DESC:     `A heavily armored, slow melee fighter. Swings from the hip but packs a huge punch.`,
		attribute.COST:     7,
		attribute.BASE_HP:  2600,
		attribute.DPS:      []int{250, 275, 302, 332, 365, 400, 440, 482},
		attribute.BASE_DAM: 450,
		attribute.HSPD:     1.8,
		attribute.TGTS:     targets.GROUND,
		attribute.SPD:      speed.SLOW,
		attribute.RNG:      lib.MELEE,
		attribute.DTIME:    3,
	})
	GOLEM = newCard(260, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Golem",
		attribute.ARENA:     arena.ARENA_6,
		attribute.RARITY:    rarity.EPIC,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!`,
		attribute.COST:      8,
		attribute.BASE_HP:   3000,
		attribute.DPS:       []int{74, 81, 90, 98, 108, 118, 130, 143},
		attribute.BASE_DAM:  186,
		attribute.BASE_DDAM: 186,
		attribute.HSPD:      2.5,
		attribute.TGTS:      targets.BUILDINGS,
		attribute.SPD:       speed.SLOW,
		attribute.RNG:       lib.MELEE,
		attribute.DTIME:     3,
	})
	DARK_PRINCE = newCard(270, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Dark Prince",
		attribute.ARENA:     arena.ARENA_7,
		attribute.RARITY:    rarity.EPIC,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `Dealing area damage with each swing and double after charging, the Dark Prince is a formidable fighter. To harm his squishy core, break his shield first.`,
		attribute.COST:      4,
		attribute.BASE_HP:   700,
		attribute.BASE_SHP:  200,
		attribute.DPS:       []int{83, 91, 100, 110, 121, 133, 146, 159},
		attribute.BASE_ADAM: 125,
		attribute.HSPD:      1.5,
		attribute.TGTS:      targets.GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       lib.MELEE,
		attribute.DTIME:     1,
	})

	// --- Legendary Troops ---
	ICE_WIZARD = newCard(350, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Ice Wizard",
		attribute.ARENA:     arena.ARENA_5,
		attribute.RARITY:    rarity.LEGENDARY,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `This chill caster hails from the far North. He shoots ice shards at enemies, slowing down their movement and attack speed.`,
		attribute.COST:      3,
		attribute.BASE_HP:   700,
		attribute.DPS:       []int{42, 46, 50, 55, 60, 67},
		attribute.BASE_ADAM: 63,
		attribute.HSPD:      1.5,
		attribute.TGTS:      targets.AIR_AND_GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       6,
		attribute.DTIME:     1,
	})
	PRINCESS = newCard(370, map[attribute.Attribute]interface{}{
		attribute.NAME:      "Princess",
		attribute.ARENA:     arena.ARENA_7,
		attribute.RARITY:    rarity.LEGENDARY,
		attribute.TYPE:      types.TROOP,
		attribute.DESC:      `Shoots a volley of flaming arrows halfway across the Arena. The Princess is afraid of germs, so keep the rabble away from her!`,
		attribute.COST:      3,
		attribute.BASE_HP:   216,
		attribute.DPS:       []int{46, 51, 56, 62, 68, 74},
		attribute.BASE_ADAM: 140,
		attribute.HSPD:      3,
		attribute.TGTS:      targets.AIR_AND_GROUND,
		attribute.SPD:       speed.MEDIUM,
		attribute.RNG:       9.5,
		attribute.DTIME:     1,
	})
)
