package card

import (
	"github.com/asukakenji/clash-royale/arena"
	"github.com/asukakenji/clash-royale/attr"
	"github.com/asukakenji/clash-royale/common"
	"github.com/asukakenji/clash-royale/rarity"
	"github.com/asukakenji/clash-royale/rng"
	"github.com/asukakenji/clash-royale/speed"
	"github.com/asukakenji/clash-royale/targets"
	"github.com/asukakenji/clash-royale/typ"
)

var troops = [...]card{
	// --- Common Troops ---
	card{
		attr.Name:    "Knight",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.`,
		attr.Elixir:  3,
		attr.BaseHP:  660,
		attr.DPS:     []interface{}{68, 74, 81, 90, 99, 109, 120, 130, 144, 158, 174, 190, common.X},
		attr.BaseDam: 75,
		attr.HSpeed:  1.1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Archers",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A pair of unarmored ranged attackers. They'll help you with ground and air unit attacks, but you're on your own with coloring your hair.`,
		attr.Elixir:  3,
		attr.BaseHP:  125,
		attr.DPS:     []interface{}{33, 36, 40, 44, 48, 53, 58, 64, 70, 77, 85, 93, common.X},
		attr.BaseDam: 40,
		attr.HSpeed:  1.2,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
		attr.Range:   5,
		attr.DTime:   1,
		attr.Count:   2,
	}.init(),
	card{
		attr.Name:     "Bomber",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Troop,
		attr.Desc:     `Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.`,
		attr.Elixir:   3,
		attr.BaseHP:   150,
		attr.DPS:      []interface{}{57, 63, 70, 76, 84, 92, 101, 111, 122, common.X, common.X, common.X, common.X},
		attr.BaseADam: 110,
		attr.HSpeed:   1.9,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    4.5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Goblins",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three fast, unarmored melee attackers. Small, fast, green and mean!`,
		attr.Elixir:  2,
		attr.BaseHP:  80,
		attr.DPS:     []interface{}{45, 50, 54, 60, 66, 72, 80, 87, 96, 105, 116, 127, 140},
		attr.BaseDam: 50,
		attr.HSpeed:  1.1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.VeryFast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Spear Goblins",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three unarmored ranged attackers. Who the heck taught these guys to throw spears!?! Who thought that was a good idea?!`,
		attr.Elixir:  2,
		attr.BaseHP:  52,
		attr.DPS:     []interface{}{18, 20, 22, 23, 26, 29, 32, 35, 38, 42, 46, 51, common.X},
		attr.BaseDam: 24,
		attr.HSpeed:  1.3,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.VeryFast,
		attr.Range:   5,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Skeletons",
		attr.Arena:   arena.Arena2,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Four fast, very weak melee fighters. Swarm your enemies with this pile of bones!`,
		attr.Elixir:  1,
		attr.BaseHP:  32,
		attr.DPS:     []interface{}{32, 35, 38, 42, 46, 51, 56, 61, 67, 74, 81, 89, 98},
		attr.BaseDam: 32,
		attr.HSpeed:  1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   4,
	}.init(),
	card{
		attr.Name:    "Minions",
		attr.Arena:   arena.Arena2,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!`,
		attr.Elixir:  3,
		attr.BaseHP:  90,
		attr.DPS:     []interface{}{40, 44, 48, 53, 58, 64, 70, 77, 84, 93, 102, 112, 123},
		attr.BaseDam: 40,
		attr.HSpeed:  1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Fast,
		attr.Range:   2,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Barbarians",
		attr.Arena:   arena.Arena3,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A horde of melee attackers with mean mustaches and even meaner tempers.`,
		attr.Elixir:  5,
		attr.BaseHP:  300,
		attr.DPS:     []interface{}{50, 54, 60, 66, 72, 80, 88, 96, 106, 116, 128, 140, common.X},
		attr.BaseDam: 75,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   4,
	}.init(),
	card{
		attr.Name:    "Minion Horde",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Six fast, unarmored flying attackers. Three's a crowd, six is a horde!`,
		attr.Elixir:  5,
		attr.BaseHP:  90,
		attr.DPS:     []interface{}{40, 44, 48, 53, 58, 64, 70, 77, 84, 93, 102, 112, 123},
		attr.BaseDam: 40,
		attr.HSpeed:  1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Fast,
		attr.Range:   2,
		attr.DTime:   1,
		attr.Count:   6,
	}.init(),
	card{
		attr.Name:     "Fire Spirits",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Troop,
		attr.Desc:     `These three Fire Spirits are on a kamikaze mission to give you a warm hug. It'd be adorable if they weren't on fire.`,
		attr.Elixir:   2,
		attr.BaseHP:   43,
		attr.BaseADam: 80,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.VeryFast,
		attr.Range:    2,
		attr.DTime:    1,
		attr.Count:    3,
	}.init(),
	card{
		attr.Name:    "Royale Giant",
		attr.Arena:   arena.Arena7,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Destroying enemy buildings with his massive cannon is his job; making a raggedy blond beard look good is his passion.`,
		attr.Elixir:  6,
		attr.BaseHP:  1200,
		attr.DPS:     []interface{}{50, common.X, common.X, common.X, common.X, common.X, 88, 96, 106, 116, common.X, common.X, common.X},
		attr.BaseDam: 75,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Buildings,
		attr.Speed:   speed.Slow,
		attr.Range:   6.5,
		attr.DTime:   1,
	}.init(),

	// --- Rare Troops ---
	card{
		attr.Name:    "Giant",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Slow but durable, only attacks buildings. A real one-man wrecking crew!`,
		attr.Elixir:  5,
		attr.BaseHP:  2000,
		attr.DPS:     []interface{}{84, 92, 101, 111, 122, 134, 147, 162, 177, 195, common.X},
		attr.BaseDam: 126,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Buildings,
		attr.Speed:   speed.Slow,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Musketeer",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.`,
		attr.Elixir:  4,
		attr.BaseHP:  340,
		attr.DPS:     []interface{}{90, 100, 110, 120, 132, 145, 160, 175, 192, 211, common.X},
		attr.BaseDam: 100,
		attr.HSpeed:  1.1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
		attr.Range:   6,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Mini P.E.K.K.A",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `The arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.`,
		attr.Elixir:  4,
		attr.BaseHP:  600,
		attr.DPS:     []interface{}{180, 198, 218, 240, 263, 288, 317, 348, 382, 420, common.X},
		attr.BaseDam: 325,
		attr.HSpeed:  1.8,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Valkyrie",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.`,
		attr.Elixir:  4,
		attr.BaseHP:  880,
		attr.DPS:     []interface{}{80, 88, 96, 106, 116, 128, 140, 154, 169, 186, common.X},
		attr.BaseDam: 120,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Hog Rider",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the arena doors.`,
		attr.Elixir:  4,
		attr.BaseHP:  800,
		attr.DPS:     []interface{}{106, 117, 128, 141, 155, 170, 187, 205, 226, 248, 272},
		attr.BaseDam: 160,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Buildings,
		attr.Speed:   speed.VeryFast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Wizard",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Troop,
		attr.Desc:     `The most awesome man to ever set foot in the arena, the Wizard will blow you away with his handsomeness... and/or fireballs.`,
		attr.Elixir:   5,
		attr.BaseHP:   340,
		attr.DPS:      []interface{}{76, 84, 92, 101, 111, 122, 134, 147, 161, 177, common.X},
		attr.BaseADam: 130,
		attr.HSpeed:   1.7,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Medium,
		attr.Range:    5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Three Musketeers",
		attr.Arena:   arena.Arena7,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Trio of power-ful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!`,
		attr.Elixir:  9,
		attr.BaseHP:  340,
		attr.DPS:     []interface{}{90, 100, 110, 120, 132, 145, 160, 175, 192, 211, common.X},
		attr.BaseDam: 100,
		attr.HSpeed:  1.1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
		attr.Range:   6,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),

	// --- Epic Troops ---
	card{
		attr.Name:      "Witch",
		attr.Arena:     arena.Arena0,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Troop,
		attr.Desc:      `Summons skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.`,
		attr.Elixir:    5,
		attr.BaseHP:    500,
		attr.DPS:       []interface{}{60, 65, 71, 78, common.X, common.X, common.X, common.X},
		attr.BaseADam:  42,
		attr.BaseSkeLV: 6,
		attr.SSpeed:    7.5,
		attr.HSpeed:    0.7,
		attr.Targets:   targets.AirAndGround,
		attr.Speed:     speed.Medium,
		attr.Range:     5,
		attr.DTime:     1,
	}.init(),
	card{
		attr.Name:    "Skeleton Army",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `Summons an army of skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.`,
		attr.Elixir:  4,
		attr.BaseHP:  32,
		attr.DPS:     []interface{}{32, 35, 38, 42, 46, 51, 56, 61},
		attr.BaseDam: 32,
		attr.HSpeed:  1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   20,
	}.init(),
	card{
		attr.Name:     "Baby Dragon",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `Flying troop that deals area damage. Baby dragons hatch cute, hungry and ready for a barbeque.`,
		attr.Elixir:   4,
		attr.BaseHP:   800,
		attr.DPS:      []interface{}{55, 61, 67, 73, 81, 88, 97, 107},
		attr.BaseADam: 100,
		attr.HSpeed:   1.8,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Fast,
		attr.Range:    3,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Prince",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Deals double damage once he gets charging.`,
		attr.Elixir:  5,
		attr.BaseHP:  1100,
		attr.DPS:     []interface{}{146, 161, 177, 194, 214, 234, 258, 282},
		attr.BaseDam: 220,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Giant Skeleton",
		attr.Arena:    arena.Arena2,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.`,
		attr.Elixir:   6,
		attr.BaseHP:   2000,
		attr.DPS:      []interface{}{66, 73, 80, 88, 97, 106, 117, 128},
		attr.BaseDam:  100,
		attr.BaseDDam: 720,
		attr.HSpeed:   1.5,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:     "Balloon",
		attr.Arena:    arena.Arena2,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.`,
		attr.Elixir:   5,
		attr.BaseHP:   1050,
		attr.DPS:      []interface{}{200, 220, 242, 266, 292, 320, 352, 386},
		attr.BaseDam:  600,
		attr.BaseDDam: 100,
		attr.HSpeed:   3,
		attr.Targets:  targets.Buildings,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "P.E.K.K.A",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `A heavily armored, slow melee fighter. Swings from the hip but packs a huge punch.`,
		attr.Elixir:  7,
		attr.BaseHP:  2600,
		attr.DPS:     []interface{}{250, 275, 302, 332, 365, 400, 440, 482},
		attr.BaseDam: 450,
		attr.HSpeed:  1.8,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Slow,
		attr.Range:   rng.Melee,
		attr.DTime:   3,
	}.init(),
	card{
		attr.Name:      "Golem",
		attr.Arena:     arena.Arena6,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Troop,
		attr.Desc:      `Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!`,
		attr.Elixir:    8,
		attr.BaseHP:    3150,
		attr.DPS:       []interface{}{74, 81, 90, 98, 108, 118, 130, 143},
		attr.BaseDam:   186,
		attr.BaseDDam:  186,
		attr.BaseGolLV: 1,
		attr.HSpeed:    2.5,
		attr.Targets:   targets.Buildings,
		attr.Speed:     speed.Slow,
		attr.Range:     rng.Melee,
		attr.DTime:     3,
	}.init(),
	card{
		attr.Name:     "Golemite",
		attr.From:     Golem,
		attr.Arena:    arena.Arena6,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     ``,
		attr.Elixir:   0,
		attr.BaseHP:   630,
		attr.BaseDam:  37,
		attr.BaseDDam: 37,
		attr.HSpeed:   2.5,
		attr.Targets:  targets.Buildings,
		attr.Speed:    speed.Slow,
	}.init(),
	card{
		attr.Name:     "Dark Prince",
		attr.Arena:    arena.Arena7,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `The Dark Prince deals area damage and lets his spiked club do the talking for him - because when he does talk, it sounds like he has a bucket on his head.`,
		attr.Elixir:   4,
		attr.BaseHP:   700,
		attr.BaseSHP:  200,
		attr.DPS:      []interface{}{83, 91, 100, 110, 121, 133, 146, 159},
		attr.BaseADam: 125,
		attr.HSpeed:   1.5,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Guards",
		attr.Arena:   arena.Arena7,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three ruthless bone brothers with shields. Knock off their shields and all that's left are three ruthless bone brothers.`,
		attr.Elixir:  3,
		attr.BaseHP:  65,
		attr.BaseSHP: 150,
		attr.DPS:     []interface{}{54, common.X, common.X, common.X, common.X, common.X, common.X, common.X},
		attr.BaseDam: 65,
		attr.HSpeed:  1.2,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),

	// --- Legendary Troops ---
	card{
		attr.Name:      "Lava Hound",
		attr.Arena:     arena.Arena4,
		attr.Rarity:    rarity.Legendary,
		attr.Type:      typ.Troop,
		attr.Desc:      `The Lava Hound is a majestic flying beast that attacks buildings. The Lava Pups are less majestic angry babies that attack anything.`,
		attr.Elixir:    7,
		attr.BaseHP:    3000,
		attr.DPS:       []interface{}{26, 29, 32, 35, 39},
		attr.BaseADam:  35,
		attr.BaseLavLV: 1,
		attr.HSpeed:    1.3,
		attr.Targets:   targets.Buildings,
		attr.Speed:     speed.Slow,
		attr.Range:     2,
		attr.DTime:     1,
	}.init(),
	card{
		attr.Name:    "Lava Pups",
		attr.From:    LavaHound,
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Legendary,
		attr.Type:    typ.Troop,
		attr.Desc:    ``,
		attr.Elixir:  0,
		attr.BaseHP:  180,
		attr.BaseDam: 45,
		attr.HSpeed:  1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
	}.init(),
	card{
		attr.Name:     "Ice Wizard",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Legendary,
		attr.Type:     typ.Troop,
		attr.Desc:     `This chill caster throws Ice Shards that slow down enemies' movement and attack speed. Despite being freezing cold, he has a handlebar mustache that's too hot for TV.`,
		attr.Elixir:   3,
		attr.BaseHP:   700,
		attr.DPS:      []interface{}{42, 46, 50, 55, 60},
		attr.BaseADam: 63,
		attr.HSpeed:   1.5,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Medium,
		attr.Range:    5.5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Miner",
		attr.Arena:   arena.Arena6,
		attr.Rarity:  rarity.Legendary,
		attr.Type:    typ.Troop,
		attr.Desc:    `The Miner can burrow his way underground and appear anywhere in the Arena. It's not magic, it's a shovel.`,
		attr.Elixir:  3,
		attr.BaseHP:  1060,
		attr.DPS:     []interface{}{133, 146, 160, 176, 194},
		attr.BaseDam: 160,
		attr.CTDam:   []interface{}{64, 71, 78, 85, 94},
		attr.HSpeed:  1.2,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Sparky",
		attr.Arena:    arena.Arena6,
		attr.Rarity:   rarity.Legendary,
		attr.Type:     typ.Troop,
		attr.Desc:     `Sparky has a heavy-handed approach to life: Obliterate everything in sight.`,
		attr.Elixir:   6,
		attr.BaseHP:   1200,
		attr.DPS:      []interface{}{260, 286, 314, 345, 379},
		attr.BaseADam: 1300,
		attr.HSpeed:   5,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Slow,
		attr.Range:    4.5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:     "Princess",
		attr.Arena:    arena.Arena7,
		attr.Rarity:   rarity.Legendary,
		attr.Type:     typ.Troop,
		attr.Desc:     `This stunning Princess shoots flaming arrows from long range. If you're feeling warm feelings towards her, it's probably because you're on fire.`,
		attr.Elixir:   3,
		attr.BaseHP:   216,
		attr.DPS:      []interface{}{46, 51, 56, 62, 68},
		attr.BaseADam: 140,
		attr.HSpeed:   3,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Medium,
		attr.Range:    9,
		attr.DTime:    1,
	}.init(),
}
